# Generated by Django 2.2.26 on 2022-02-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_testingsaap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testnews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yestest', models.URLField()),
                ('oktest', models.TextField()),
            ],
        ),
    ]
