# Generated by Django 2.2.26 on 2022-02-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_testcheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eee', models.URLField()),
                ('ee', models.TimeField()),
            ],
        ),
    ]
