# Generated by Django 2.2.26 on 2022-02-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ytest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuuut', models.URLField()),
                ('ttty', models.TimeField()),
                ('yttyy', models.UUIDField()),
            ],
        ),
    ]
